[{"author": {"state": "active", "avatar_url": "http://cdn.libravatar.org/avatar/b4c7afc2cdffea95a8c2d0387acedc6b?s=40&d=identicon", "id": 15, "name": "Paulo Meireles", "username": "paulormm"}, "id": 13191, "body": "_Assignee removed_", "created_at": "2016-05-19T02:59:52.000Z", "attachment": null}, {"author": {"state": "active", "avatar_url": "http://cdn.libravatar.org/avatar/4f4b696adc8e8769f43b5c837b3ea23b?s=40&d=identicon", "id": 6, "name": "Marisa Souza dos Santos", "username": "marisa"}, "id": 13106, "body": "talvez possamos deixar do jeito que est\u00e1, n\u00e3o vai fazer diferen\u00e7a se n resolveremos em definitivo. reabrir-backlog", "created_at": "2016-05-18T14:48:36.861Z", "attachment": null}, {"author": {"state": "active", "avatar_url": "http://cdn.libravatar.org/avatar/b862b39de0eaa58597cae9cdb6b4b13d?s=40&d=identicon", "id": 72, "name": "Matheus Fernandes", "username": "msfernandes"}, "id": 11787, "body": "@lmatos infelizmente, esse bug est\u00e1 fora do nosso alcance... O que acontece \u00e9 um erro na tradu\u00e7\u00e3o do django: escreveram errado a url  para quando o sistema estiver em portugu\u00eas :( \r\nFarei um merge request para o django assim que for poss\u00edvel para arrumar esse bug, mas n\u00e3o podemos garantir a atualiza\u00e7\u00e3o dele...\r\n\r\nComo medida provis\u00f3ria, quando for atualizar a senha de um usu\u00e1rio, voce pode adicionar \"/password/\" no final da url da p\u00e1gina, por exemplo:\r\n\r\nA p\u00e1gina do painel de admnistra\u00e7\u00e3o que edita os dados do usu\u00e1rio \u00e9 algo do tipo: \r\n\r\nsoftwarepublico.gov.br/colab/admin/accounts/user/5/\r\n\r\nEnt\u00e3o, a url para alterar a senha seria:\r\n\r\nsoftwarepublico.gov.br/colab/admin/accounts/user/5/password/\r\n", "created_at": "2016-04-20T20:59:23.360Z", "attachment": null}, {"author": {"state": "active", "avatar_url": "http://cdn.libravatar.org/avatar/71c7041f7667454f3d6bf8f889e2d598?s=40&d=identicon", "id": 1253, "name": "Luiz Matos", "username": "lmatos"}, "id": 11791, "body": "Ol\u00e1 @msfernandes, ciente. Vamos ver melhor na segunda.", "created_at": "2016-04-20T21:01:32.919Z", "attachment": null}, {"author": {"state": "active", "avatar_url": "http://cdn.libravatar.org/avatar/b862b39de0eaa58597cae9cdb6b4b13d?s=40&d=identicon", "id": 72, "name": "Matheus Fernandes", "username": "msfernandes"}, "id": 11789, "body": "_Status changed to closed_", "created_at": "2016-04-20T21:00:17.697Z", "attachment": null}, {"author": {"state": "active", "avatar_url": "http://cdn.libravatar.org/avatar/b862b39de0eaa58597cae9cdb6b4b13d?s=40&d=identicon", "id": 72, "name": "Matheus Fernandes", "username": "msfernandes"}, "id": 11788, "body": "_Milestone changed to Backlog_", "created_at": "2016-04-20T21:00:15.480Z", "attachment": null}, {"author": {"state": "active", "avatar_url": "http://cdn.libravatar.org/avatar/b862b39de0eaa58597cae9cdb6b4b13d?s=40&d=identicon", "id": 72, "name": "Matheus Fernandes", "username": "msfernandes"}, "id": 11775, "body": "N\u00e3o conseguimos reproduzir esse erro em ambiente de desenvolvimento por ser c\u00f3digo interno do framework... Assim que o ambiente de dev terminar de convergir fa\u00e7o os testes la", "created_at": "2016-04-20T18:56:04.672Z", "attachment": null}, {"author": {"state": "active", "avatar_url": "http://cdn.libravatar.org/avatar/71c7041f7667454f3d6bf8f889e2d598?s=40&d=identicon", "id": 1253, "name": "Luiz Matos", "username": "lmatos"}, "id": 11087, "body": "@marisa para conhecimento", "created_at": "2016-04-12T17:04:19.977Z", "attachment": null}]