[{"author": {"state": "active", "avatar_url": "http://cdn.libravatar.org/avatar/a8ff67a0e69e7cfaeb1299e02082c339?s=40&d=identicon", "id": 3, "name": "Arthur Esposte", "username": "arthurmde"}, "id": 7541, "body": "_Status changed to closed_", "created_at": "2016-01-07T19:31:30.360Z", "attachment": null}, {"author": {"state": "active", "avatar_url": "http://cdn.libravatar.org/avatar/a8ff67a0e69e7cfaeb1299e02082c339?s=40&d=identicon", "id": 3, "name": "Arthur Esposte", "username": "arthurmde"}, "id": 7540, "body": "@maxalmeida e @rodrigo pelo que vi, essa discuss\u00e3o foi finalizada. Vou fechar a issue por enquanto, mas caso achem necess\u00e1rio podem abr\u00ed-la novamente e conversamos quando devemos atac\u00e1-la!", "created_at": "2016-01-07T19:31:30.046Z", "attachment": null}, {"author": {"state": "active", "avatar_url": "http://cdn.libravatar.org/avatar/2eecd4b7edebcb887e143c62846b2048?s=40&d=identicon", "id": 7, "name": "Rodrigo Siqueira de Melo", "username": "rodrigo"}, "id": 5141, "body": "@maxalmeida est\u00e1 tarefa foi finalizada? Eu tenho a impress\u00e3o de que nunca mais tivemos problemas com isto.", "created_at": "2015-11-12T11:36:18.441Z", "attachment": null}, {"author": {"state": "active", "avatar_url": "http://cdn.libravatar.org/avatar/8f652615179e2c91f88085cb0c7c9e5c?s=40&d=identicon", "id": 85, "name": "Maxwell Max", "username": "maxalmeida"}, "id": 2812, "body": "@davidcarlos ", "created_at": "2015-08-25T14:38:15.715Z", "attachment": null}, {"author": {"state": "active", "avatar_url": "http://cdn.libravatar.org/avatar/8f652615179e2c91f88085cb0c7c9e5c?s=40&d=identicon", "id": 85, "name": "Maxwell Max", "username": "maxalmeida"}, "id": 2811, "body": "N\u00e3o, t\u00e1 aberta.Na \u00faltima atualiza\u00e7\u00e3o feita no mpog ,passamos por uma situa\u00e7\u00e3o que n\u00e3o haviamos previsto antes.O ambiente ja havia subido mas uma das m\u00e1quinas(database) teve que ser reconstru\u00edda.Quando demos o converge a task de setup do gitlab nunca era executada.\r\n\r\nPara contornar isso fizemos dois procedimentos.O primeiro foi entrar no diret\u00f3rio do gitlab na integration e remover um arquivo criado pela receita para dar \"lock\" no banco. Uma vez que a task de setup s\u00f3 deve ser executada uma vez , e ela ja havia sido executada porque o ambiente ja estava \"convergido\".Rodamos o converge de novo e isso n\u00e3o foi o suficente para permitir que o mesmo fosse executado corretamente.Fizemos um segundo procedimento que foi alterar o arquivo database.yml , pois a task de setup quando h\u00e1 uma altera\u00e7\u00e3o neste arquivo ela \u00e9 executada corretamente.Dado isso , precisamos tornar a receita mais robusta para que ela possa prever esse tipo de situa\u00e7\u00e3o e evitar que essas altera\u00e7\u00f5es manuais tenham que ser feitas.", "created_at": "2015-08-25T14:37:26.324Z", "attachment": null}, {"author": {"state": "active", "avatar_url": "http://cdn.libravatar.org/avatar/2eecd4b7edebcb887e143c62846b2048?s=40&d=identicon", "id": 7, "name": "Rodrigo Siqueira de Melo", "username": "rodrigo"}, "id": 2779, "body": "@maxalmeida eu n\u00e3o entendi direito que problema \u00e9 este. Esta issue j\u00e1 est\u00e1 fechada? Do contr\u00e1rio, sugiro um detalhamento maior da mesma.", "created_at": "2015-08-25T10:00:05.973Z", "attachment": null}]